#! /bin/bash
set -e -u

S3_BUCKET=hackforprivacy.org

docker-compose run --rm --service-ports awscli aws s3 sync public/ s3://${S3_BUCKET} --acl public-read --region ap-southeast-2 --delete --cache-control "max-age=300,s-maxage=300"
